### PR TITLE
Make the makefile to compile code into libmbed-client-mbedtls.a

### PR DESCRIPTION
**Pull request by TeroJaasko**
Make the makefile to produce a library out of the sources defined
in sources.mk. This makes it possible to use this code eg. from
nanosimulator.

### CODE REVIEW

**Comment by TeroJaasko** [comment]
@anttiylitokola @ErkkiMehtala @teetak01 @yogpan01

**Comment by yogpan01** [comment]
The introduction of mbed-trace has broken the Makefile approach for our mbed-client. mbed-trace has to be included as part of nanomesh-application repository and it needs to be pulled in. Currently our nanomesh-application pulls in ns-trace but now that we have moved to using mbed-trace we need our Makefile to be fixed to start using mbed-trace library. Not sure if both ns-trace and mbed-trace repos. can co-exist but this needs to be fixed otherwise our nanosimulator builds will not compile.

**Comment by teetak01** [comment]
rebuild

**Comment by TeroJaasko** [comment]
I'd rather not try to do nanostack wide conversion from ns-trace to mbed-trace, or try to support both of them in same build of simulator. I just added a compatibility wrapper type of hack in commit: https://github.com/ARMmbed/nanomesh-applications/pull/178/commits/67879f3f64c20f7ca29506d7f657f8d0074b9b70.

**Pull request merged**
