### PR TITLE
Adding ignore file for build system.

### PR DESCRIPTION
**Pull request by yogpan01**

### CODE REVIEW

**Comment by anttiylitokola** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by c1728p9** [comment]
@anttiylitokola, @yogpan01, can this be merged?  Once this is in I'll make a PR to the master branch of mbed-os

**Comment by yogpan01** [comment]
@c1728p9 This is now merged, you can go ahead and create PR for master branch.
@anttiylitokola We need to fix CI build job for this component, it is currently broken. I pushed this PR now because it is needed for integration.

**Pull request merged**
